Добавление теста №1 для шифра Цезаря в main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,7 +6,7 @@ on:
   pull_request:
 
 jobs:
-  build-caesar:
+  test-caesar:
     runs-on: ubuntu-latest
 
     defaults:
@@ -14,7 +14,7 @@ jobs:
         working-directory: backend/Caesar
 
     steps:
-      - name: Получение кода из репозитория
+      - name: Получение кода
         uses: actions/checkout@v4
 
       - name: Установка JDK
@@ -26,11 +26,16 @@ jobs:
       - name: Компиляция
         run: javac src/Caesar.java
 
-      - name: Запуск
+      - name: Тест 1 - Шифрование английского текста
         run: |
-          printf "1\n3\n" | java -cp src Caesar # Автоматически подаём данные в программу: шифрование - 1, сдвиг - 3
-
-      - name: Чтение output.txt
-        run: |
-          echo "===== output.txt ====="
-          cat output.txt
+          echo "Test Caesar cipher." > input.txt
+          printf "1\n3\n" | java -cp src Caesar
+          expected="Whvw Fdhvdu flskhu."
+          result=$(cat output.txt)
+          echo "EXPECTED: $expected"
+          echo "RESULT:   $result"
+          if [ "$expected" != "$result" ]; then
+            echo "Test 1 failed!"
+            exit 1
+          fi
+          echo "Test 1 passed!"
